# Based upon recommendations in https://stackoverflow.com/questions/41916656

os: linux
dist: trusty
language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7

before_install:
  - pip install --user cpp-coveralls
  
script:
  - export CC=gcc-7
  - export CXX=g++-7
  - gcc -v && g++ -v && cmake --version
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - ctest

after_success:
  - coveralls --root .. -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"
